### ISSUE TITLE
support for traktor s4

### ISSUE THREAD

**Issue by melnikalex** [artemvm/traktor_s5_mod#1]
Hi, love this mod. Will you ever mod the traktor s4 as well?

Thanks!

**Comment by artemvmin** [comment]
Sorry, the traktor s4 tempo sliders are too smart for my dumb, little brain.

P.S. Love how the decks go all **spinny spinny**.

**Comment by artemvmin** [comment]
Update: I decided to mod the s4

https://github.com/artemvmin/traktor_s4mk3_mod
